### ISSUE TITLE
createRouter click event handler doesn't have chance to fire

### ISSUE THREAD

**Issue by Guria** [logux/state#17]
I just tried createRouter with following snippet:

```
const router = createRouter<Routes>({
  home: '/',
  category: '/posts/:categoryId',
  post: '/posts/:categoryId/:id'
});

console.log(getValue(router));
const a = document.createElement('a');
a.href = getPagePath(router, 'post', { categoryId: 'guides', id: '10' });
a.text = 'Link';

document.body.append(a);
```
Clicking on the link appended to a document led to browser page "reload" instead of pushing new url using history API.
I have checked sources and it seems intention was to handle all same origin clicks with router click handler and preventing default behavior. I was able to fix it by passing `{ capture: true }` option to `addEventListener` call.

I can prepare PR with a fix, but just want to double check that I don't missing out anything.
I also see that this covered in tests but most likely jsdom doesn't provide "navigate out" emulation.

**Comment by ai** [comment]
Yeap, seems like a forgot about that option

**Comment by Guria** [comment]
Ok, I found that changing to `capture: true` breaks test `ignores prevented events`. And to be honest, I can't find a way to make it work other then markink with data attribute. And it already supported but not covered with test. So I will convert this test to use data attribute

**Comment by ai** [comment]
Hm. Very strange. Why this option break `e.preventDefault` and why it fixed that issue?

**Comment by Guria** [comment]
Here is demo of current behaviour:
https://7vu8g.csb.app/
https://codesandbox.io/s/trusting-dew-7vu8g?file=/src/index.ts
You can see that page reloads and timer resets.

I've tried to put `debugger` statement into click handler and it was unable to stop without adding `capture: true`;

On the other side complete "vanila" example shows that it should be possible:
https://codesandbox.io/s/crazy-darkness-7ienv?file=/src/index.ts

**Comment by Guria** [comment]
checking further

**Comment by Guria** [comment]
Figured out that just log value in my case cause unsubscrubing. Adding `router.subscribe(() => {})` fixes an issue.
And adding `capture: true` on the other hand shouldn't help at all.
Sorry about confusion and great you were attentive enough. I will update my PR to have only meaningful parts: added test and fixed docs.
