### ISSUE TITLE
createRouter support history replaceState

### ISSUE THREAD

**Issue by Guria** [logux/state#19]
Sometimes we need to replace latest state in history (aka redirect).
I am proposing following API changes:
```ts
router.open(path: string, redirect?: boolean);

// additional export that will pass flag to open
export function redirectPage(router, name, params);
```
It increases bundle-size on 13 B.

Please approve or give another suggestions and I will prepare PR.

**Comment by ai** [comment]
13 bytes is OK.

But can we add it as a separated function without `router.open` changes? If not, send PR with `redirect` argument.

**Comment by Guria** [comment]
![image](https://user-images.githubusercontent.com/36270/120374428-97567300-c32a-11eb-9416-249329b3dc66.png)

![image](https://user-images.githubusercontent.com/36270/120375543-fbc60200-c32b-11eb-8159-4c4d9ccdc8dd.png)

Both seems to cost same 13 bytes, but I still like single `open` method with `redirect` argument more, since it only single statement change needed. Though it also looks a little bit hacky.

Letting you to decide before going to cover it with tests :)

**Comment by ai** [comment]
I mean of adding `redirect(router, url)` top-level function

**Comment by Guria** [comment]
both variants has top-level `redirectPage(router, name,params)`
